name: XPOptimizer
version: 3.1.0
main: com.xpoptimizer.XPOptimizerPlugin
api-version: '1.21'
description: Zero-allocation direct XP deposit with mending support, multipliers, stats, and effects
author: Tom
